Unit Test for EmailService
amoraitis/TodoList pull request #35
Opened 2019-10-05 08:49 UTC by Gokilarajan

The unit test is to make sure if there are no exception thrown if the email service is not able to send the email.

2019-10-06 10:00 UTC, ghost requested changes

2019-10-06 10:00 UTC, reerden commented on TodoList.UnitTests/Services/EmailSenderTest.cs
> +               .ReturnsAsync(new Response(System.Net.HttpStatusCode.InternalServerError, _httpContentMock.Object, null));
Please add this reference (`using System.Net`) to keep the code small.

2019-10-14 17:12 UTC, Gokilarajan commented on TodoList.UnitTests/Services/EmailSenderTest.cs
> +               .ReturnsAsync(new Response(System.Net.HttpStatusCode.InternalServerError, _httpContentMock.Object, null));
The System.Net is added as Namespace.

2019-10-19 09:25 UTC, amoraitis requested changes
Can you please update your working branch and resolve any conflicts?

2019-10-23 23:03 UTC, Gokilarajan commented
> Can you please update your working branch and resolve any conflicts?

Yes it is done

2019-10-24 06:25 UTC, amoraitis requested changes

2019-10-24 06:25 UTC, amoraitis commented on TodoList.UnitTests/Services/EmailSenderTest.cs
> +            EmailSender _emailSenderService = new EmailSender(_sendGridClientMock.Object, new SendGridMessage(),_logger);
If this is a local variable, can we please remove the `_`?

2019-10-25 04:31 UTC, amoraitis approved these changes
Thank you for improving the tests!

2019-10-25 04:31 UTC, merged